import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy, doc, updateDoc, addDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0",authDomain:"prayer-projec.firebaseapp.com",projectId:"prayer-projec",storageBucket:"prayer-projec.firebasestorage.app",messagingSenderId:"47966669764",appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const adminRequests=$('adminRequests'),statusFilter=$('statusFilter'),sortFilter=$('sortFilter'),adminSearch=$('adminSearch'),quickFilters=$('quickFilters'),notice=$('dashboardNotice');
let requests=[],reports=[],notes=[],activeQuickFilter='all';

injectModalStyles();
createAdminModal();

onAuthStateChanged(auth,async user=>{if(!user){window.location.href='login.html';return;}await loadDashboard();});
statusFilter?.addEventListener('change',renderRequests);
sortFilter?.addEventListener('change',renderRequests);
adminSearch?.addEventListener('input',renderRequests);
quickFilters?.addEventListener('click',e=>{const b=e.target.closest('.quick-filter');if(!b)return;activeQuickFilter=b.dataset.quick||'all';quickFilters.querySelectorAll('.quick-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRequests();});

async function loadDashboard(){try{setNotice('Loading requests...');if(adminRequests)adminRequests.innerHTML='<div class="empty">Loading prayer requests...</div>';await Promise.all([loadRequests(),loadReports(),loadNotes()]);renderRequests();setNotice(`Loaded ${requests.length} request${requests.length===1?'':'s'}.`);}catch(e){console.error(e);if(adminRequests)adminRequests.innerHTML='<div class="empty">Requests could not load. Check Firestore rules and indexes.</div>';setNotice('Requests could not load.');}}
async function loadRequests(){const s=await getDocs(query(collection(db,'prayer_requests'),orderBy('createdAt','desc')));requests=[];s.forEach(d=>requests.push({id:d.id,...d.data()}));}
async function loadReports(){try{const s=await getDocs(query(collection(db,'reports'),orderBy('createdAt','desc')));reports=[];s.forEach(d=>reports.push({id:d.id,...d.data()}));}catch{reports=[];}}
async function loadNotes(){try{const s=await getDocs(query(collection(db,'admin_notes'),orderBy('createdAt','desc')));notes=[];s.forEach(d=>notes.push({id:d.id,...d.data()}));}catch{notes=[];}}

function renderRequests(){if(!adminRequests)return;const filter=statusFilter?.value||'all',term=(adminSearch?.value||'').toLowerCase().trim(),sort=sortFilter?.value||'newest';let visible=filter==='all'?[...requests]:requests.filter(r=>(r.status||'approved')===filter);visible=visible.filter(r=>activeQuickFilter==='urgent'?!!r.urgent:activeQuickFilter==='reported'?(r.status||'approved')==='reported'||getReportCount(r.id)>0:activeQuickFilter==='answered'?!!r.answered:activeQuickFilter==='unanswered'?!r.answered:activeQuickFilter==='no-email'?!r.email:true);if(term)visible=visible.filter(r=>`${r.title||''} ${r.message||''} ${r.category||''} ${r.email||''} ${r.answeredTestimony||''} ${getNotes(r.id).map(n=>n.note).join(' ')} ${reports.filter(x=>x.requestId===r.id).map(x=>x.reason).join(' ')}`.toLowerCase().includes(term));visible.sort((a,b)=>sort==='oldest'?time(a.createdAt)-time(b.createdAt):sort==='mostPrayed'?(b.prayerCount||0)-(a.prayerCount||0):sort==='mostReported'?getReportCount(b.id)-getReportCount(a.id):sort==='urgentFirst'?Number(!!b.urgent)-Number(!!a.urgent)||time(b.createdAt)-time(a.createdAt):sort==='answeredFirst'?Number(!!b.answered)-Number(!!a.answered)||time(b.createdAt)-time(a.createdAt):time(b.createdAt)-time(a.createdAt));if(!visible.length){adminRequests.innerHTML='<div class="empty">No prayer requests found for this filter.</div>';return;}adminRequests.innerHTML=visible.map(card).join('');document.querySelectorAll('.status-select').forEach(s=>s.onchange=()=>setStatus(s.dataset.id,s.value));document.querySelectorAll('.answered-select').forEach(s=>s.onchange=()=>setAnswered(s.dataset.id,s.value==='true'));document.querySelectorAll('.urgency-select').forEach(s=>s.onchange=()=>setUrgent(s.dataset.id,s.value==='true'));document.querySelectorAll('.add-note').forEach(b=>b.onclick=()=>openNoteModal(b.dataset.id));document.querySelectorAll('.edit-note').forEach(b=>b.onclick=()=>openEditNoteModal(b.dataset.id));document.querySelectorAll('.delete-note').forEach(b=>b.onclick=()=>confirmDeleteNote(b.dataset.id));document.querySelectorAll('.delete-report').forEach(b=>b.onclick=()=>confirmDeleteReport(b.dataset.id));document.querySelectorAll('.edit-request').forEach(b=>b.onclick=()=>openEditModal(b.dataset.id));document.querySelectorAll('.resolve-reports').forEach(b=>b.onclick=()=>resolveReports(b.dataset.id));}
function card(r){const reps=reports.filter(x=>x.requestId===r.id),ns=getNotes(r.id),status=r.status||'approved',date=r.createdAt?.toDate?r.createdAt.toDate().toLocaleString():'Recently';return `<article class="item"><span class="pill ${status==='reported'?'warn':status==='approved'?'ok':''}">${esc(status)}</span><h3>${esc(r.title)} ${r.answered?'<span class="pill ok">Answered</span>':''}</h3><p>${esc(r.message)}</p><div class="meta"><span>Category: ${esc(r.category)}</span><span>Prayers: ${r.prayerCount||0}</span><span>Reports: ${reps.length}</span><span>Notes: ${ns.length}</span><span>${date}</span>${r.urgent?'<span>Urgent</span>':''}</div><div class="meta"><span>Email: ${esc(r.email||'No email saved')}</span></div><div class="status-grid"><label>Status<select class="status-select" data-id="${r.id}"><option value="approved" ${status==='approved'?'selected':''}>Approved</option><option value="reported" ${status==='reported'?'selected':''}>Reported</option><option value="removed" ${status==='removed'?'selected':''}>Removed</option><option value="pending" ${status==='pending'?'selected':''}>Pending</option></select></label><label>Answered<select class="answered-select" data-id="${r.id}"><option value="false" ${!r.answered?'selected':''}>No</option><option value="true" ${r.answered?'selected':''}>Yes</option></select></label><label>Urgency<select class="urgency-select" data-id="${r.id}"><option value="false" ${!r.urgent?'selected':''}>Normal</option><option value="true" ${r.urgent?'selected':''}>Urgent</option></select></label></div>${r.answeredTestimony?`<div class="notice"><strong>Answered Update</strong><br>${esc(r.answeredTestimony)}</div>`:''}${reps.length?`<div class="notice"><strong>Reports</strong>${reps.map(x=>`<div class="admin-row"><p>${esc(x.reason)} — ${esc(x.status||'open')}</p><button class="mini-action delete-report" data-id="${x.id}" type="button">Delete</button></div>`).join('')}</div>`:''}${ns.length?`<div class="notice"><strong>Admin Notes</strong>${ns.map(n=>`<div class="admin-row"><p>${esc(n.note)}</p><div><button class="mini-action edit-note" data-id="${n.id}" type="button">Edit</button><button class="mini-action danger delete-note" data-id="${n.id}" type="button">Delete</button></div></div>`).join('')}</div>`:''}<div class="toolbar"><button class="btn neutral add-note" data-id="${r.id}">Add Note</button><button class="btn neutral edit-request" data-id="${r.id}">Edit Request</button><button class="btn neutral resolve-reports" data-id="${r.id}">Resolve Reports</button></div></article>`;}
function openNoteModal(id){showModal({title:'Private Admin Note',intro:'Add a note that only admins can see.',fields:[{id:'note',label:'Note',type:'textarea',rows:5,placeholder:'Type the admin note...'}],submitText:'Save Note',onSubmit:async values=>{if(!values.note.trim())throw new Error('Please enter a note.');await addDoc(collection(db,'admin_notes'),{requestId:id,note:values.note.trim(),adminEmail:auth.currentUser?.email||'Admin',createdAt:serverTimestamp()});await audit('added_note',id);await loadDashboard();}})}
function openEditNoteModal(noteId){const n=notes.find(x=>x.id===noteId);if(!n)return;showModal({title:'Edit Admin Note',intro:'Update this private note.',fields:[{id:'note',label:'Note',type:'textarea',rows:5,value:n.note||''}],submitText:'Save Note',onSubmit:async values=>{if(!values.note.trim())throw new Error('Please enter a note.');await updateDoc(doc(db,'admin_notes',noteId),{note:values.note.trim(),editedAt:serverTimestamp(),editedBy:auth.currentUser?.email||'Admin'});await audit('edited_note',n.requestId||noteId);await loadDashboard();}})}
function confirmDeleteNote(noteId){const n=notes.find(x=>x.id===noteId);showModal({title:'Delete Admin Note',intro:'This will permanently delete this admin note.',fields:[],submitText:'Delete Note',onSubmit:async()=>{await deleteDoc(doc(db,'admin_notes',noteId));await audit('deleted_note',n?.requestId||noteId);await loadDashboard();}})}
function confirmDeleteReport(reportId){const r=reports.find(x=>x.id===reportId);showModal({title:'Delete Report',intro:'This will permanently delete this report record. It will not delete the prayer request itself.',fields:[],submitText:'Delete Report',onSubmit:async()=>{await deleteDoc(doc(db,'reports',reportId));await audit('deleted_report',r?.requestId||reportId);await loadDashboard();}})}
function openEditModal(id){const r=requests.find(x=>x.id===id);if(!r)return;showModal({title:'Edit Prayer Request',intro:'Update the public request text without using browser prompts.',fields:[{id:'title',label:'Title',value:r.title||''},{id:'message',label:'Message',type:'textarea',rows:6,value:r.message||''},{id:'category',label:'Category',value:r.category||''},{id:'email',label:'Email',value:r.email||''}],submitText:'Save Changes',onSubmit:async v=>{if(!v.title.trim()||!v.message.trim())throw new Error('Title and message are required.');await updateDoc(doc(db,'prayer_requests',id),{title:v.title.trim(),message:v.message.trim(),category:v.category.trim()||'Other',email:v.email.trim(),updatedAt:serverTimestamp()});await audit('edited_request',id);await loadDashboard();}})}
async function setStatus(id,status){await updateDoc(doc(db,'prayer_requests',id),{status,updatedAt:serverTimestamp()});await audit('status_'+status,id);await loadDashboard();}
async function setAnswered(id,answered){await updateDoc(doc(db,'prayer_requests',id),answered?{answered:true,answeredAt:serverTimestamp(),updatedAt:serverTimestamp()}:{answered:false,answeredTestimony:'',updatedAt:serverTimestamp()});await audit(answered?'marked_answered':'undid_answered',id);await loadDashboard();}
async function setUrgent(id,urgent){await updateDoc(doc(db,'prayer_requests',id),{urgent,updatedAt:serverTimestamp()});await audit(urgent?'marked_urgent':'marked_normal',id);await loadDashboard();}
async function resolveReports(id){for(const rep of reports.filter(r=>r.requestId===id))await updateDoc(doc(db,'reports',rep.id),{status:'resolved',resolvedAt:serverTimestamp(),resolvedBy:auth.currentUser?.email||'Admin'});await audit('resolved_reports',id);await loadDashboard();}
async function audit(action,requestId){try{await addDoc(collection(db,'audit_logs'),{action,requestId,adminEmail:auth.currentUser?.email||'Admin',createdAt:serverTimestamp()});}catch(e){console.warn(e);}}
function createAdminModal(){if($('adminModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="admin-modal" id="adminModal" aria-hidden="true"><div class="admin-modal-backdrop" data-close-modal></div><section class="admin-modal-card" role="dialog" aria-modal="true"><button class="admin-modal-close" data-close-modal type="button">×</button><div class="eyebrow">Admin Action</div><h2 id="modalTitle">Admin</h2><p id="modalIntro"></p><form id="modalForm"><div id="modalFields"></div><div class="admin-modal-error" id="modalError"></div><div class="admin-modal-actions"><button class="btn neutral" data-close-modal type="button">Cancel</button><button class="btn btn-primary" id="modalSubmit" type="submit">Save</button></div></form></section></div>`);document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});}
function showModal(config){const modal=$('adminModal'),form=$('modalForm'),fields=$('modalFields'),error=$('modalError'),submit=$('modalSubmit');$('modalTitle').textContent=config.title;$('modalIntro').textContent=config.intro||'';submit.textContent=config.submitText||'Save';error.textContent='';fields.innerHTML=(config.fields||[]).map(f=>`<label class="admin-modal-field">${esc(f.label)}${f.type==='textarea'?`<textarea id="modal_${f.id}" rows="${f.rows||4}" placeholder="${esc(f.placeholder||'')}">${esc(f.value||'')}</textarea>`:`<input id="modal_${f.id}" value="${esc(f.value||'')}" placeholder="${esc(f.placeholder||'')}">`}</label>`).join('');form.onsubmit=async e=>{e.preventDefault();error.textContent='';submit.disabled=true;submit.textContent='Working...';try{const values={};(config.fields||[]).forEach(f=>values[f.id]=$(`modal_${f.id}`).value);await config.onSubmit(values);closeModal();}catch(err){error.textContent=err.message||'This action failed.';}finally{submit.disabled=false;submit.textContent=config.submitText||'Save';}};modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');setTimeout(()=>fields.querySelector('input,textarea')?.focus(),50);}
function closeModal(){const modal=$('adminModal');if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
function injectModalStyles(){if($('adminModalStyles'))return;const style=document.createElement('style');style.id='adminModalStyles';style.textContent=`.status-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.status-grid label,.admin-modal-field{display:grid;gap:8px;color:var(--muted);font-size:12px;font-weight:900}.admin-row{display:flex;gap:10px;align-items:center;justify-content:space-between;border-top:1px solid rgba(255,255,255,.08);padding:10px 0}.admin-row:first-of-type{border-top:0}.admin-row p{margin:0!important}.mini-action{border:1px solid rgba(216,195,165,.18);background:rgba(255,255,255,.06);color:var(--warm2);border-radius:999px;padding:7px 10px;font-size:11px;font-weight:900;cursor:pointer}.mini-action.danger,.mini-action.delete-report{color:var(--danger);border-color:rgba(255,211,211,.22)}.admin-modal{position:fixed;inset:0;z-index:9999;display:none;align-items:center;justify-content:center;padding:18px}.admin-modal.show{display:flex}.admin-modal-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.82);backdrop-filter:blur(14px)}.admin-modal-card{position:relative;width:min(660px,100%);max-height:calc(100vh - 36px);overflow:auto;padding:30px;border-radius:32px;background:linear-gradient(180deg,rgba(19,17,15,.98),rgba(5,5,5,.98));border:1px solid rgba(216,195,165,.22);box-shadow:0 35px 120px rgba(0,0,0,.85);color:var(--text)}.admin-modal-card h2{font-family:"Playfair Display",serif;font-size:42px;line-height:1;margin:16px 0 10px}.admin-modal-card p{color:var(--muted);line-height:1.7}.admin-modal-close{position:absolute;right:18px;top:18px;width:40px;height:40px;border-radius:50%;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);color:var(--text);font-size:24px}.admin-modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.admin-modal-error{color:var(--danger);font-weight:800;min-height:20px;margin-top:12px}.modal-open{overflow:hidden}@media(max-width:760px){.status-grid{grid-template-columns:1fr}.admin-row{align-items:flex-start;flex-direction:column}.admin-modal-card{padding:24px}.admin-modal-card h2{font-size:34px}.admin-modal-actions{flex-direction:column}.admin-modal-actions .btn{width:100%}}`;document.head.appendChild(style);}
function getReportCount(id){return reports.filter(x=>x.requestId===id).length}function getNotes(id){return notes.filter(x=>x.requestId===id)}function time(t){return t?.toDate?t.toDate().getTime():0}function setNotice(t){if(notice)notice.textContent=t}function esc(t=''){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}