import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy, doc, updateDoc, setDoc, getDoc, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";

const firebaseConfig = { apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0", authDomain:"prayer-projec.firebaseapp.com", projectId:"prayer-projec", storageBucket:"prayer-projec.firebasestorage.app", messagingSenderId:"47966669764", appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291" };
const EMAIL_ENDPOINT = "https://script.google.com/macros/s/AKfycbxdmttZIR8nCYr_613OEpsH7p1OFO19sHOyW04tacpRHC05VUthelEPRCr9KcUQdE5xxw/exec";
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);
const el = id => document.getElementById(id);
const adminRequests = el("adminRequests"), requestCount = el("requestCount"), prayerCount = el("prayerCount"), urgentCount = el("urgentCount"), emailCount = el("emailCount"), reportedCount = el("reportedCount"), removedCount = el("removedCount"), statusFilter = el("statusFilter"), sortFilter = el("sortFilter"), adminSearch = el("adminSearch"), adminEmail = el("adminEmail"), logoutBtn = el("logoutBtn"), refreshBtn = el("refreshBtn"), exportBtn = el("exportBtn"), quickFilters = el("quickFilters"), moderationQueue = el("moderationQueue"), dashboardNotice = el("dashboardNotice"), dailyVerse = el("dailyVerse"), dailyVerseReference = el("dailyVerseReference"), homepageAnnouncement = el("homepageAnnouncement"), submissionsOpen = el("submissionsOpen"), saveSettingsBtn = el("saveSettingsBtn"), settingsNotice = el("settingsNotice");
let requests = [], reports = [], notes = [], logs = [], visibleRequests = [], activeQuickFilter = "all";

onAuthStateChanged(auth, async user => { if (!user) { window.location.href = "login.html"; return; } adminEmail.textContent = user.email || "Admin"; await Promise.all([loadDashboard(), loadSettings()]); });
logoutBtn?.addEventListener("click", async () => { await signOut(auth); window.location.href = "login.html"; });
statusFilter?.addEventListener("change", renderRequests); sortFilter?.addEventListener("change", renderRequests); adminSearch?.addEventListener("input", renderRequests); refreshBtn?.addEventListener("click", loadDashboard); exportBtn?.addEventListener("click", copyVisibleSummary); saveSettingsBtn?.addEventListener("click", saveSettings);
quickFilters?.addEventListener("click", event => { const button = event.target.closest(".quick-filter"); if (!button) return; activeQuickFilter = button.dataset.quick || "all"; quickFilters.querySelectorAll(".quick-filter").forEach(item => item.classList.remove("active")); button.classList.add("active"); renderRequests(); });

async function loadDashboard(){ try { dashboardNotice.textContent = "Refreshing dashboard..."; adminRequests.innerHTML = '<div class="empty">Loading prayer requests...</div>'; await Promise.all([loadRequests(), loadReports(), loadNotes(), loadLogs()]); renderRequests(); updateStatistics(); renderModerationQueue(); dashboardNotice.textContent = `Dashboard refreshed. ${requests.length} request${requests.length === 1 ? "" : "s"} loaded.`; } catch (error) { console.error(error); adminRequests.innerHTML = '<div class="empty">Failed to load admin dashboard. Check Firestore rules and login permissions.</div>'; dashboardNotice.textContent = "Dashboard failed to load."; } }
async function loadRequests(){ const snap = await getDocs(query(collection(db,"prayer_requests"), orderBy("createdAt","desc"))); requests=[]; snap.forEach(d=>requests.push({id:d.id,...d.data()})); }
async function loadReports(){ const snap = await getDocs(query(collection(db,"reports"), orderBy("createdAt","desc"))); reports=[]; snap.forEach(d=>reports.push({id:d.id,...d.data()})); }
async function loadNotes(){ try{ const snap = await getDocs(query(collection(db,"admin_notes"), orderBy("createdAt","desc"))); notes=[]; snap.forEach(d=>notes.push({id:d.id,...d.data()})); }catch{ notes=[]; } }
async function loadLogs(){ try{ const snap = await getDocs(query(collection(db,"audit_logs"), orderBy("createdAt","desc"))); logs=[]; snap.forEach(d=>logs.push({id:d.id,...d.data()})); }catch{ logs=[]; } }

function renderRequests(){
  const filter = statusFilter?.value || "all", term = (adminSearch?.value || "").toLowerCase().trim(), sort = sortFilter?.value || "newest";
  let visible = filter === "all" ? [...requests] : requests.filter(r => (r.status || "approved") === filter);
  visible = visible.filter(r => activeQuickFilter === "urgent" ? !!r.urgent : activeQuickFilter === "reported" ? (r.status || "approved") === "reported" || getReportCount(r.id) > 0 : activeQuickFilter === "answered" ? !!r.answered : activeQuickFilter === "unanswered" ? !r.answered : activeQuickFilter === "no-email" ? !r.email : true);
  if (term) visible = visible.filter(r => `${r.title||""} ${r.message||""} ${r.category||""} ${r.email||""} ${r.answeredTestimony||""} ${getNotes(r.id).map(n=>n.note).join(" ")}`.toLowerCase().includes(term));
  visible.sort((a,b) => sort === "oldest" ? getTime(a.createdAt) - getTime(b.createdAt) : sort === "mostPrayed" ? (b.prayerCount || 0) - (a.prayerCount || 0) : sort === "mostReported" ? getReportCount(b.id) - getReportCount(a.id) : sort === "urgentFirst" ? Number(!!b.urgent) - Number(!!a.urgent) || getTime(b.createdAt) - getTime(a.createdAt) : sort === "answeredFirst" ? Number(!!b.answered) - Number(!!a.answered) || getTime(b.createdAt) - getTime(a.createdAt) : getTime(b.createdAt) - getTime(a.createdAt));
  visibleRequests = visible;
  if(!visible.length){ adminRequests.innerHTML='<div class="empty">No prayer requests found for this filter.</div>'; return; }
  adminRequests.innerHTML = visible.map(r=>{ const date = r.createdAt?.toDate ? r.createdAt.toDate().toLocaleString() : "Recently"; const matchingReports = reports.filter(x=>x.requestId===r.id); const requestNotes = getNotes(r.id); const status = r.status || "approved"; return `<article class="request ${r.answered ? 'answered-admin' : ''} ${status === 'reported' ? 'reported-admin' : ''}"><h3>${esc(r.title)} <span class="status-pill ${status === "reported" ? "reported" : ""}">${esc(status)}</span>${r.answered ? '<span class="answered-pill">Answered!</span>' : ''}</h3><p>${esc(r.message)}</p><div class="meta"><span>Category: ${esc(r.category)}</span><span>Prayers: ${r.prayerCount||0}</span><span>Reports: ${matchingReports.length}</span><span>Notes: ${requestNotes.length}</span><span>Submitted: ${date}</span>${r.urgent?'<span>Urgent</span>':''}</div><div class="meta"><span>Email: ${esc(r.email || "No email saved")}</span><span>Answered: ${r.answered ? 'Yes' : 'No'}</span></div>${r.answeredTestimony?`<div class="reportbox answered-box"><strong>Answered Testimony</strong><p>${esc(r.answeredTestimony)}</p></div>`:""}${matchingReports.length?`<div class="reportbox"><strong>Reports</strong>${matchingReports.map(x=>`<p>${esc(x.reason)} — ${esc(x.status||"open")}</p>`).join("")}</div>`:""}${requestNotes.length?`<div class="reportbox"><strong>Admin Notes</strong>${requestNotes.map(n=>`<p>${esc(n.note)}</p>`).join("")}</div>`:""}<div class="toolbar"><button class="btn approve" data-action="approved" data-id="${r.id}">Return to Wall</button><button class="btn warn" data-action="reported" data-id="${r.id}">Keep Reported</button><button class="btn delete" data-action="removed" data-id="${r.id}">Remove</button>${r.answered ? `<button class="btn neutral undo-answered" data-id="${r.id}">Undo Answered</button>` : `<button class="btn approve mark-answered" data-id="${r.id}">Mark Answered</button>`}<button class="btn neutral add-note" data-id="${r.id}">Add Note</button><button class="btn neutral edit-request" data-id="${r.id}">Edit</button><button class="btn neutral resolve-reports" data-id="${r.id}">Resolve Reports</button></div></article>`; }).join("");
  document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>setStatus(b.dataset.id,b.dataset.action)));
  document.querySelectorAll(".undo-answered").forEach(b=>b.addEventListener("click",()=>setAnswered(b.dataset.id,false)));
  document.querySelectorAll(".mark-answered").forEach(b=>b.addEventListener("click",()=>setAnswered(b.dataset.id,true)));
  document.querySelectorAll(".add-note").forEach(b=>b.addEventListener("click",()=>addAdminNote(b.dataset.id)));
  document.querySelectorAll(".edit-request").forEach(b=>b.addEventListener("click",()=>editRequest(b.dataset.id)));
  document.querySelectorAll(".resolve-reports").forEach(b=>b.addEventListener("click",()=>resolveReports(b.dataset.id)));
}
function renderModerationQueue(){ if (!moderationQueue) return; const queue = requests.filter(r => (r.status || "approved") === "reported" || getReportCount(r.id) > 0).slice(0,8); const recent = logs.slice(0,5).map(l=>`<div class="mini-item"><strong>${esc(l.action||"Action")}</strong><br>${esc(l.adminEmail||"Admin")} · ${esc(l.requestId||"")}</div>`).join(""); moderationQueue.innerHTML = (queue.length ? queue.map(r => `<div class="mini-item"><strong>${esc(r.title)}</strong><br>Status: ${esc(r.status || "approved")} · Reports: ${getReportCount(r.id)}</div>`).join("") : '<div class="mini-item">No reported requests are currently waiting for review.</div>') + (recent ? `<div class="mini-item"><strong>Recent Audit Log</strong></div>${recent}` : ""); }
async function setStatus(id,status){ await updateDoc(doc(db,"prayer_requests",id),{status,updatedAt:serverTimestamp()}); await audit("status_"+status,id); await loadDashboard(); }
async function setAnswered(id,answered){ const update = answered ? {answered:true,answeredAt:serverTimestamp(),updatedAt:serverTimestamp()} : {answered:false,answeredTestimony:"",updatedAt:serverTimestamp()}; await updateDoc(doc(db,"prayer_requests",id),update); await audit(answered?"marked_answered":"undid_answered",id); await loadDashboard(); }
async function addAdminNote(id){ const note = prompt("Private admin note:"); if(!note || !note.trim()) return; await addDoc(collection(db,"admin_notes"),{requestId:id,note:note.trim(),adminEmail:auth.currentUser?.email||"Admin",createdAt:serverTimestamp()}); await audit("added_note",id); await loadDashboard(); }
async function editRequest(id){ const r = requests.find(x=>x.id===id); if(!r) return; const title = prompt("Edit title:", r.title||""); if(title===null) return; const message = prompt("Edit message:", r.message||""); if(message===null) return; await updateDoc(doc(db,"prayer_requests",id),{title:title.trim(),message:message.trim(),updatedAt:serverTimestamp()}); await audit("edited_request",id); await loadDashboard(); }
async function resolveReports(id){ const list = reports.filter(r=>r.requestId===id); for(const report of list){ await updateDoc(doc(db,"reports",report.id),{status:"resolved",resolvedAt:serverTimestamp(),resolvedBy:auth.currentUser?.email||"Admin"}); } await audit("resolved_reports",id); await loadDashboard(); }
async function audit(action,requestId){ try{ await addDoc(collection(db,"audit_logs"),{action,requestId,adminEmail:auth.currentUser?.email||"Admin",createdAt:serverTimestamp()}); }catch(error){ console.warn("Audit log not saved",error); } }
function updateStatistics(){ requestCount.textContent=requests.length; prayerCount.textContent=requests.reduce((s,r)=>s+(r.prayerCount||0),0); urgentCount.textContent=requests.filter(r=>r.urgent).length; emailCount.textContent=requests.filter(r=>r.answered).length; if(reportedCount) reportedCount.textContent=requests.filter(r=>(r.status||"approved")==="reported").length; if(removedCount) removedCount.textContent=requests.filter(r=>(r.status||"approved")==="removed").length; }
async function loadSettings(){ try { const settingsDoc = await getDoc(doc(db,"settings","site")); if(!settingsDoc.exists()) return; const data = settingsDoc.data(); dailyVerse.value = data.dailyVerse || ""; dailyVerseReference.value = data.dailyVerseReference || ""; homepageAnnouncement.value = data.homepageAnnouncement || ""; submissionsOpen.value = String(data.submissionsOpen ?? true); } catch (error) { console.error(error); settingsNotice.textContent = "Failed to load settings."; } }
async function saveSettings(){ try { saveSettingsBtn.disabled = true; saveSettingsBtn.textContent = "Saving..."; await setDoc(doc(db,"settings","site"),{ dailyVerse: dailyVerse.value.trim(), dailyVerseReference: dailyVerseReference.value.trim(), homepageAnnouncement: homepageAnnouncement.value.trim(), submissionsOpen: submissionsOpen.value === "true", lastSettingsUpdate:new Date().toISOString(), updatedAt: serverTimestamp() },{merge:true}); await audit("saved_settings","settings/site"); settingsNotice.textContent = "Settings saved successfully."; dashboardNotice.textContent = "Site settings saved successfully."; } catch (error) { console.error(error); settingsNotice.textContent = "Failed to save settings. Check Firestore rules."; } finally { saveSettingsBtn.disabled = false; saveSettingsBtn.textContent = "Save Settings"; } }
async function copyVisibleSummary(){ const text = visibleRequests.map(r => `${r.title || "Untitled"} | ${r.status || "approved"} | ${r.category || ""} | ${r.prayerCount || 0} prayers | ${getReportCount(r.id)} reports`).join("\n"); try { await navigator.clipboard.writeText(text || "No visible requests."); dashboardNotice.textContent = "Visible request summary copied."; } catch { dashboardNotice.textContent = "Copy failed. Your browser may have blocked clipboard access."; } }
function getReportCount(id){ return reports.filter(x=>x.requestId===id).length; }
function getNotes(id){ return notes.filter(x=>x.requestId===id); }
function getTime(timestamp){ return timestamp?.toDate ? timestamp.toDate().getTime() : 0; }
function esc(t=""){ return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;"); }