import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy, doc, updateDoc, addDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0",authDomain:"prayer-projec.firebaseapp.com",projectId:"prayer-projec",storageBucket:"prayer-projec.firebasestorage.app",messagingSenderId:"47966669764",appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),list=document.getElementById('reportList'),search=document.getElementById('reportSearch'),status=document.getElementById('reportStatus');let reports=[],requests=[];
onAuthStateChanged(auth,async user=>{if(!user){window.location.href='login.html';return;}injectStyles();await load();});
search.addEventListener('input',render);status.addEventListener('change',render);
async function load(){try{const [rs,ps]=await Promise.all([getDocs(query(collection(db,'reports'),orderBy('createdAt','desc'))),getDocs(collection(db,'prayer_requests'))]);reports=[];requests=[];rs.forEach(d=>reports.push({id:d.id,...d.data()}));ps.forEach(d=>requests.push({id:d.id,...d.data()}));render();}catch(e){console.error(e);list.innerHTML='<div class="empty">Reports could not load. Check Firestore rules.</div>';}}
function render(){const term=(search.value||'').toLowerCase().trim(),filter=status.value;let visible=reports.filter(r=>(filter==='all'||(r.status||'open')===filter)&&`${r.reason||''} ${r.requestId||''}`.toLowerCase().includes(term));list.innerHTML=visible.length?visible.map(r=>{const req=requests.find(x=>x.id===r.requestId);return `<article class="item"><span class="pill ${r.status==='resolved'?'ok':'warn'}">${esc(r.status||'open')}</span><h3>${esc(req?.title||'Unknown request')}</h3><p>${esc(r.reason||'No reason provided')}</p><div class="meta"><span>Request: ${esc(r.requestId||'')}</span><span>${date(r.createdAt)}</span></div><div class="toolbar"><button class="btn approve return-wall" data-request="${r.requestId}" data-report="${r.id}">Return Request</button><button class="btn neutral resolve" data-report="${r.id}">Resolve Report</button><button class="btn delete remove-request" data-request="${r.requestId}" data-report="${r.id}">Remove Request</button><button class="btn delete delete-report" data-report="${r.id}">Delete Report</button></div></article>`}).join(''):'<div class="empty">No reports match this filter.</div>';document.querySelectorAll('.resolve').forEach(b=>b.onclick=()=>resolveReport(b.dataset.report));document.querySelectorAll('.return-wall').forEach(b=>b.onclick=()=>setRequest(b.dataset.request,b.dataset.report,'approved'));document.querySelectorAll('.remove-request').forEach(b=>b.onclick=()=>setRequest(b.dataset.request,b.dataset.report,'removed'));document.querySelectorAll('.delete-report').forEach(b=>b.onclick=()=>deleteReport(b.dataset.report));}
async function resolveReport(id){await updateDoc(doc(db,'reports',id),{status:'resolved',resolvedAt:serverTimestamp(),resolvedBy:auth.currentUser?.email||'Admin'});await audit('resolved_report',id);await load();}
async function deleteReport(id){const report=reports.find(r=>r.id===id);const ok=confirm('Delete this report permanently?');if(!ok)return;await deleteDoc(doc(db,'reports',id));await audit('deleted_report',report?.requestId||id);await load();}
async function setRequest(requestId,reportId,newStatus){await updateDoc(doc(db,'prayer_requests',requestId),{status:newStatus,updatedAt:serverTimestamp()});await resolveReport(reportId);await audit('report_set_request_'+newStatus,requestId);}
async function audit(action,target){try{await addDoc(collection(db,'audit_logs'),{action,requestId:target,adminEmail:auth.currentUser?.email||'Admin',createdAt:serverTimestamp()});}catch(e){console.warn(e)}}
function injectStyles(){if(document.getElementById('reportAdminStyles'))return;const style=document.createElement('style');style.id='reportAdminStyles';style.textContent='@media(max-width:760px){.toolbar .btn{width:100%}}';document.head.appendChild(style)}
function date(t){return t?.toDate?t.toDate().toLocaleString():'Recently'}function esc(t=''){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}